name: Automated Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Run Test Case 1
      run: |
        python find_lowest_number.py test_data/test1_input.txt test_data/output1.txt
        diff test_data/output1.txt test_data/test1_expected.txt

    - name: Run Test Case 2
      run: |
        python find_lowest_number.py test_data/test2_input.txt test_data/output2.txt
        diff test_data/output2.txt test_data/test2_expected.txt

    - name: Run Test Case 3
      run: |
        python find_lowest_number.py test_data/test3_input.txt test_data/output3.txt
        diff test_data/output3.txt test_data/test3_expected.txt
